import card1 from '../images/assets/images/Card1.png'
import card2 from '../images/assets/images/Card2.png'
import card3 from '../images/assets/images/Card3.png'
import star from '../images/assets/images/star.png'

export const data =[{
          id: 1,
          img: card1,
          imgicon : star,
          rating: '5.0',
          number: '(6) ●USA',
          para: 'Life lesson with Kattie Zeferes',
          para2: 'From $126',
          showPresence: "Online",
          openSpots: 0,
},
{
  id: 2,
  img: card3,   
  imgicon : star,
  rating: '4.8',
  number: '(30) ●USA',
  para: 'Group Mountain Biking',
  para2: 'From $130',
  showPresence: "Offline",
  openSpots: 27,
},
{
  id: 3,
  img: card2,
  imgicon : star,
  rating: '5.0',
  number: '(6) ●USA',
  para: 'Learn wedding photography',
  para2: 'From $125',
  showPresence: "Online",
  openSpots: 3,
},
{
  id: 4,
  img: card1,
  imgicon : star,
  rating: '5.0',
  number: '(6) ●USA',
  para: 'Life lesson with Kattie Zeferes',
  para2: 'From $126',
  showPresence: "Online",
  openSpots: 0,
},
{
id: 5,
img: card3,
imgicon : star,
rating: '4.8',
number: '(30) ●USA',
para: 'Group Mountain Biking',
para2: 'From $130',
showPresence: "Offline",
openSpots: 27,
},
{
id: 6,
img: card2,
imgicon : star,
rating: '5.0',
number: '(6) ●USA',
para: 'Learn wedding photography',
para2: 'From $125',
showPresence: "Online",
openSpots: 3,
},
{
  id: 7,
  img: card1,
  imgicon : star,
  rating: '5.0',
  number: '(6) ●USA',
  para: 'Life lesson with Kattie Zeferes',
  para2: 'From $126',
  showPresence: "Online",
  openSpots: 0,
},
{
id: 8,
img: card3,
imgicon : star,
rating: '4.8',
number: '(30) ●USA',
para: 'Group Mountain Biking',
para2: 'From $130',
showPresence: "Offline",
openSpots: 27,
},
{
id: 9,
img: card2,
imgicon : star,
rating: '5.0',
number: '(6) ●USA',
para: 'Learn wedding photography',
para2: 'From $125',
showPresence: "Online",
openSpots: 3,
},
{
id: 10,
img: card1,
imgicon : star,
rating: '5.0',
number: '(6) ●USA',
para: 'Life lesson with Kattie Zeferes',
para2: 'From $126',
showPresence: "Online",
openSpots: 0,
},
{
id: 11,
img: card3,
imgicon : star,
rating: '4.8',
number: '(30) ●USA',
para: 'Group Mountain Biking',
para2: 'From $130',
showPresence: "Offline",
openSpots: 27,
},
{
id: 12,
img: card2,
imgicon : star,
rating: '5.0',
number: '(6) ●USA',
para: 'Learn wedding photography',
para2: 'From $125',
showPresence: "Online",
openSpots: 3,
}
]